spring.application.name=order-processing-shipments

jwt.secret=${JWT_SECRET}

# disabling; REST services only here
spring.jpa.open-in-view=false

# ship props
com.orderprocessing.ship.page-size=50
com.orderprocessing.ship.max-page-size=50
com.orderprocessing.ship.shipment-sorting-attribute=shipped,desc
com.orderprocessing.ship.fulfillment-sorting-attribute=created,desc

# Feign communication control
orders.service.url=http://localhost:8081/orders
enable.feign.notifications=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when-authorized
management.endpoint.loggers.access=unrestricted

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
