spring.application.name=order-processing-shipments

jwt.secret=${JWT_SECRET}

# disabling; REST services only here
spring.jpa.open-in-view=false

# ship props
orders.demo.ship.page-size=50
orders.demo.ship.max-page-size=50
orders.demo.ship.shipment-sorting-attribute=shipped,desc
orders.demo.ship.fulfillment-sorting-attribute=created,desc

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
